@frontDoorUrl = https://<front-door-endpoint-host>
@webAppUrl = https://yourappname-web.azurewebsites.net

### Front Door home page
GET {{frontDoorUrl}}/
Accept: text/html

### Front Door health endpoint
GET {{frontDoorUrl}}/healthz
Accept: application/json

### Front Door operations info
GET {{frontDoorUrl}}/ops/info
Accept: application/json

### Direct web app health endpoint
GET {{webAppUrl}}/healthz
Accept: application/json
